package structs

type CollegePlayerResponse struct {
	FirstName             string
	LastName              string
	Position              string
	Age                   int
	Year                  int
	State                 string
	Country               string
	Stars                 int
	Height                string
	PotentialGrade        string
	Shooting2Grade        string
	Shooting3Grade        string
	FreeThrowGrade        string
	FinishingGrade        string
	BallworkGrade         string
	ReboundingGrade       string
	InteriorDefenseGrade  string
	PerimeterDefenseGrade string
	Stamina               int
	PlaytimeExpectations  int
	InsideProportion      uint
	MidRangeProportion    uint
	ThreePointProportion  uint
	PositionOne           string
	PositionTwo           string
	PositionThree         string
	P1Minutes             int
	P2Minutes             int
	P3Minutes             int
	Minutes               int
	Potential             int
	OverallGrade          string
	Personality           string
	RecruitingBias        string
	WorkEthic             string
	AcademicBias          string
	PlayerID              uint
	TeamID                uint
	TeamAbbr              string
	IsRedshirting         bool
	IsRedshirt            bool
	SeasonStats           CollegePlayerSeasonStats
}

type NBAPlayerResponse struct {
	FirstName             string
	LastName              string
	Position              string
	Age                   int
	Year                  int
	State                 string
	Country               string
	Stars                 int
	Height                string
	PotentialGrade        string
	Shooting2Grade        string
	Shooting3Grade        string
	FreeThrowGrade        string
	FinishingGrade        string
	BallworkGrade         string
	ReboundingGrade       string
	InteriorDefenseGrade  string
	PerimeterDefenseGrade string
	Stamina               int
	PlaytimeExpectations  int
	Minutes               int
	Potential             int
	OverallGrade          string
	Personality           string
	RecruitingBias        string
	WorkEthic             string
	AcademicBias          string
	PlayerID              uint
	TeamID                uint
	TeamAbbr              string
	IsRedshirting         bool
	IsRedshirt            bool
	SeasonStats           NBAPlayerSeasonStats
}
