package structs

type TeamSeasonStatsResponse struct {
	ID                        uint
	TeamID                    uint
	SeasonID                  uint
	GamesPlayed               uint
	Points                    int
	PointsAgainst             int
	PPG                       float64
	PAPG                      float64
	Possessions               int
	PossessionsPerGame        float64
	FGM                       int
	FGA                       int
	FGPercent                 float64
	FGMPG                     float64
	FGAPG                     float64
	FGMAgainst                int
	FGAAgainst                int
	FGPercentAgainst          float64
	FGMAPG                    float64
	FGAAPG                    float64
	ThreePointsMade           int
	ThreePointAttempts        int
	ThreePointPercent         float64
	ThreePointsMadeAgainst    int
	ThreePointAttemptsAgainst int
	ThreePointPercentAgainst  float64
	TPMPG                     float64
	TPAPG                     float64
	TPMAPG                    float64
	TPAAPG                    float64
	FTM                       int
	FTA                       int
	FTPercent                 float64
	FTMPG                     float64
	FTAPG                     float64
	FTMAgainst                int
	FTAAgainst                int
	FTMAPG                    float64
	FTAAPG                    float64
	FTPercentAgainst          float64
	Rebounds                  int
	OffRebounds               int
	DefRebounds               int
	ReboundsPerGame           float64
	OffReboundsPerGame        float64
	DefReboundsPerGame        float64
	ReboundsAllowed           int
	OffReboundsAllowed        int
	DefReboundsAllowed        int
	ReboundsAllowedPerGame    float64
	OffReboundsAllowedPerGame float64
	DefReboundsAllowedPerGame float64
	Assists                   int
	AssistsAllowed            int
	AssistsPerGame            float64
	AssistsAllowedPerGame     float64
	Steals                    int
	StealsAllowed             int
	StealsPerGame             float64
	StealsAllowedPerGame      float64
	Blocks                    int
	BlocksAllowed             int
	BlocksPerGame             float64
	BlocksAllowedPerGame      float64
	TotalTurnovers            int
	TurnoversAllowed          int
	TurnoversPerGame          float64
	TurnoversAllowedPerGame   float64
	Fouls                     int
	FoulsPerGame              float64
	PointsDiff                float64
	FGMDiff                   float64
	FGADiff                   float64
	FGPercentDiff             float64
	TPMDiff                   float64
	TPADiff                   float64
	TPPercentDiff             float64
	FTMDiff                   float64
	FTADiff                   float64
	FTPercentDiff             float64
	OReboundsDiff             float64
	DReboundsDiff             float64
	ReboundsDiff              float64
	AssistsDiff               float64
	StealsDiff                float64
	BlocksDiff                float64
	TODiff                    float64
	FoulsDiff                 float64
}
