package util

import "golang.org/x/exp/slices"

func CheckIfStringInList(val string, list []string) bool {
	return slices.Contains(list, val)
}

func GetAdjacentCountryMap() map[string][]string {
	return map[string][]string{
		"England":            {"Scotland", "Ireland", "Wales", "France"},
		"Scotland":           {"England", "Ireland", "Wales", "Iceland"},
		"Ireland":            {"Scotland", "England", "Wales"},
		"Wales":              {"Scotland", "Ireland", "England"},
		"France":             {"Andorra", "Spain", "Belgium", "Germany", "Luxembourg", "Italy", "England"},
		"Andorra":            {"France", "Spain"},
		"Belgium":            {"France", "Germany", "Luxembourg", "Netherlands"},
		"Spain":              {"Portugal", "Andorra", "France", "Morocco"},
		"Netherlands":        {"Belgium", "Germany", "Luxembourg"},
		"Germany":            {"Belgium", "France", "Luxembourg", "Netherlands", "Switzerland", "Austria", "Czechia", "Poland", "Denmark"},
		"Denmark":            {"Germany", "Sweden", "Norway", "Iceland"},
		"Norway":             {"Denmark", "Sweden", "Finland", "Iceland"},
		"Sweden":             {"Finland", "Denmark", "Norway", "Iceland"},
		"Iceland":            {"Finland", "Sweden", "Norway", "Denmark"},
		"Finland":            {"Russia", "Sweden", "Norway", "Iceland", "Estonia"},
		"Poland":             {"Germany", "Czechia", "Slovakia", "Ukraine", "Russia", "Lithuania"},
		"Lithuania":          {"Poland", "Latvia", "Estonia", "Ukraine"},
		"Latvia":             {"Lithuania", "Estonia", "Russia"},
		"Estonia":            {"Lithuania", "Latvia", "Russia", "Finland"},
		"Russia":             {"Finland", "Estonia", "Latvia", "Ukraine", "Kazakhstan", "Azerbaijan", "Mongolia", "China"},
		"Ukraine":            {"Russia", "Moldova", "Romania", "Poland", "Slovakia", "Hungary"},
		"Czechia":            {"Germany", "Austria", "Slovakia", "Poland"},
		"Slovakia":           {"Czechia", "Poland", "Hungary", "Ukraine"},
		"Austria":            {"Germany", "Italy", "Slovenia", "Czechia", "Slovakia", "Hungary"},
		"Hungary":            {"Austria", "Slovakia", "Romania", "Serbia", "Croatia", "Slovenia"},
		"Romania":            {"Hungary", "Moldova", "Ukraine", "Serbia", "Bulgaria"},
		"Slovenia":           {"Austria", "Hungary", "Croatia", "Italy"},
		"Croatia":            {"Slovenia", "Bosnia", "Serbia", "Hungary"},
		"Bosnia":             {"Croatia", "Serbia", "Montenegro", "Kosovo"},
		"Montenegro":         {"Bosnia", "Serbia", "Kosovo", "Albania"},
		"Kosovo":             {"Montenegro", "Serbia", "Bosnia", "Albania", "North Macedonia", "Greece"},
		"Serbia":             {"Hungary", "Kosovo", "Romania", "Bosnia", "Croatia", "Bulgaria", "Montenegro"},
		"Bulgaria":           {"Greece", "Turkey", "Romania", "Serbia", "North Macedonia"},
		"Albania":            {"Greece", "North Macedonia", "Kosovo", "Serbia", "Montenegro", "Bosnia"},
		"Greece":             {"Albania", "Turkey", "North Macedonia", "Bulgaria", "Italy", "Cyprus"},
		"Italy":              {"Malta", "France", "Slovenia", "Austria", "Croatia", "Greece", "Tunisia"},
		"Turkey":             {"Greece", "Bulgaria", "Cyprus", "Syria", "Georgia", "Armenia", "Iran", "Iraq"},
		"Cyprus":             {"Greece", "Italy", "Turkey", "Lebanon", "Israel", "Syria", "Egypt"},
		"Morocco":            {"Spain", "Algeria", "Mauritania"},
		"Algeria":            {"Morocco", "Tunisia", "Libya", "Niger", "Mali", "Mauritania"},
		"Tunisia":            {"Algeria", "Libya", "Malta", "Italy"},
		"Libya":              {"Algeria", "Tunisia", "Egypt", "Chad", "Niger", "Sudan"},
		"Mali":               {"Mauritania", "Niger", "Burkina Faso", "Ivory Coast", "Guinea", "Senegal"},
		"Senegal":            {"Mauritania", "Mali", "The Gambia", "Guinea"},
		"The Gambia":         {"Senegal", "Guinea"},
		"Guinea":             {"Mali", "The Gambia", "Senegal", "Sierra Leone", "Liberia", "Ivory Coast"},
		"Liberia":            {"Sierra Leone", "Guinea", "Ivory Coast"},
		"Ivory Coast":        {"Liberia", "Guinea", "Mali", "Burkina Faso", "Ghana"},
		"Ghana":              {"Ivory Coast", "Burkina Faso", "Togo"},
		"Sierra Leone":       {"Guinea", "Liberia"},
		"Togo":               {"Ghana", "Burkina Faso", "Benin"},
		"Benin":              {"Togo", "Burkina Faso", "Nigeria", "Niger"},
		"Niger":              {"Nigeria", "Chad", "Mali", "Algeria", "Libya", "Benin"},
		"Nigeria":            {"Benin", "Niger", "Cameroon", "Chad"},
		"Chad":               {"Niger", "Nigeria", "Cameroon", "Central African Republic", "Sudan"},
		"Cameroon":           {"Nigeria", "Chuad", "Central African Republic", "Gabon", "Congo"},
		"Gabon":              {"Cameroon", "Congo"},
		"Congo":              {"Gabon", "DRC", "Cameroon"},
		"DRC":                {"Congo", "Central African Republic", "South Sudan", "Uganda", "Rwanda", "Burundi", "Tanzania", "Zambia", "Angola"},
		"Angola":             {"DRC", "Zambia", "Namibia"},
		"Zambia":             {"Angola", "DRC", "Zimbabwe", "Malawi", "Tanzania", "Mozambique"},
		"Namibia":            {"Angola", "Botswana", "South Africa", "Zimbabwe"},
		"Botswana":           {"Namibia", "Zimbabwe", "South Africa", "Zambia"},
		"South Africa":       {"Namibia", "Botswana", "Zimbabwe", "Mozambique", "Eswatini", "Lesotho", "Madagascar"},
		"Zimbabwe":           {"Zambia", "Namibia", "Botswana", "Mozambique"},
		"Mozambique":         {"Madagascar", "South Africa", "Zimbabwe", "Malawi", "Zambia", "Tanzania"},
		"Malawi":             {"Zambia", "Mozambique", "Tanzania"},
		"Madagascar":         {"South Africa", "Mozambique", "Tanzania"},
		"Tanzania":           {"Madagascar", "Zambia", "Burundi", "Rwanda", "Uganda", "Kenya", "DRC"},
		"Rwanda":             {"Burundi", "Tanzania", "DRC", "Uganda"},
		"Burundi":            {"Rwanda", "DRC", "Tanzania"},
		"Kenya":              {"Uganda", "Tanzania", "Somalia", "Ethiopia", "South Sudan"},
		"Somalia":            {"Kenya", "Ethiopia", "Djibouti"},
		"Uganda":             {"DRC", "South Sudan", "Kenya", "Tanzania", "Rwanda"},
		"Ethiopia":           {"Djibouti", "Somalia", "Kenya", "South Sudan", "Eritrea", "Sudan"},
		"Djibouti":           {"Ethiopia", "Eritrea", "Somalia", "Yemen"},
		"Eritrea":            {"Ethiopia", "Sudan", "Djibouti", "Yemen", "Saudi Arabia"},
		"Sudan":              {"Libya", "Egypt", "Chad", "South Sudan", "Central African Republic", "Ethiopia", "Eritrea"},
		"Egypt":              {"Libya", "Sudan", "Cyprus", "Israel", "Palestine", "Saudi Arabia"},
		"Israel":             {"Egypt", "Palestine", "Lebanon", "Cyprus", "Greece", "Jordan", "Syria"},
		"Palestine":          {"Egypt", "Israel", "Jordan", "Cyprus"},
		"Jordan":             {"Israel", "Saudi Arabia", "Syria", "Iraq"},
		"Lebanon":            {"Israel", "Cyprus", "Syria", "Turkey"},
		"Syria":              {"Lebanon", "Israel", "Turkey", "Iraq", "Jordan"},
		"Iraq":               {"Turkey", "Syria", "Jordan", "Saudi Arabia", "Kuwait", "Iran"},
		"Iran":               {"Iraq", "Armenia", "Azerbaijan", "Turkmenistan", "Afghanistan", "Pakistan", "UAE", "Qatar"},
		"Kuwait":             {"Iraq", "Iran", "Saudia Arabia", "Bahrain", "Qatar", "UAE"},
		"Saudi Arabia":       {"Egypt", "Jordan", "Iraq", "Yemen", "Oman", "Bahrain", "Qatar", "UAE"},
		"Bahrain":            {"Qatar", "Saudi Arabia", "Kuwait", "Iran", "UAE"},
		"Qatar":              {"Bahrain", "Saudi Arabia", "UAE", "Iran"},
		"Yemen":              {"Djibouti", "Eritrea", "Saudi Arabia", "Oman"},
		"Oman":               {"UAE", "Yemen", "Saudi Arabia", "Iran"},
		"UAE":                {"Saudi Arabia", "Oman", "Qatar", "Bahrain", "Kuwait", "Iran"},
		"Georgia":            {"Russia", "Armenia", "Turkey", "Azerbaijan"},
		"Armenia":            {"Georgia", "Turkey", "Azerbaijan", "Iran"},
		"Azerbaijan":         {"Georgia", "Armenia", "Russia", "Iran"},
		"Afghanistan":        {"Iran", "Turkmenistan", "Tajikistan", "Uzbekistan", "Pakistan"},
		"Uzbekistan":         {"Turkmenistan", "Kazakhstan", "Afghanistan", "Tajikistan", "Kyrgyzstan"},
		"Turkmenistan":       {"Iran", "Afghanistan", "Uzbekistan", "Kazakhstan"},
		"Tajikistan":         {"Uzbekistan", "Afghanistan", "Kyrgyzstan", "China"},
		"Kyrgyzstan":         {"China", "Kazakhstan", "Tajikistan", "Uzbekistan"},
		"Kazakhstan":         {"China", "Kyrgyzstan", "Russia", "Uzbekistan"},
		"Pakistan":           {"Iran", "Afghanistan", "India"},
		"India":              {"Pakistan", "Nepal", "Bangladesh", "Bhutan", "China"},
		"Nepal":              {"India", "China"},
		"Bangladesh":         {"India", "Myanmar"},
		"Myanmar":            {"India", "China", "Bangladesh", "Thailand", "Laos"},
		"Thailand":           {"Myanmar", "Laos", "Cambodia", "Malaysia"},
		"Laos":               {"Myanmar", "Thailand", "Cambodia", "China", "Vietnam"},
		"Cambodia":           {"Thailand", "China", "Laos", "Vietnam"},
		"Vietnam":            {"Cambodia", "China", "Laos", "Philippines"},
		"China":              {"India", "Kazakhstan", "Russia", "Mongolia", "HK", "Singapore", "Tajikistan", "Myanmar", "Laos", "Vietnam", "Taiwan", "Japan", "South Korea"},
		"Mongolia":           {"Russia", "China"},
		"South Korea":        {"Japan", "China", "Taiwan"},
		"Japan":              {"South Korea", "China", "Taiwan"},
		"Taiwan":             {"HK", "China", "Singapore", "Philippines"},
		"HK":                 {"Taiwan", "China", "Philippines"},
		"Malaysia":           {"Thailand", "Singapore", "Indonesia"},
		"Singapore":          {"HK", "China", "Taiwan", "Malaysia", "Indonesia"},
		"Indonesia":          {"Malaysia", "Papua New Guinea", "Philippines", "Australia"},
		"Philippines":        {"Vietnam", "China", "HK", "Taiwan", "Indonesia", "China"},
		"Papua New Guinea":   {"Indonesia", "Australia", "Solomon Islands", "New Caledonia"},
		"Australia":          {"Indonesia", "Papua New Guinea", "New Caledonia", "Norfolk Island", "New Zealand", "Fiji", "French Polynesia", "Vanuatu"},
		"New Zealand":        {"Papua New Guinea", "New Caledonia", "Norfolk Island", "Australia", "Fiji", "French Polynesia", "Vanuatu"},
		"Fiji":               {"Australia", "New Zealand"},
		"New Caledonia":      {"Australia", "New Zealand"},
		"Solomon Islands":    {"Australia", "New Zealand"},
		"Norfolk Island":     {"Australia", "New Zealand"},
		"Mexico":             {"Cuba", "Puerto Rico", "Dominican Republic", "Guatemala"},
		"Cuba":               {"Mexico", "Puerto Rico", "Dominican Republic", "Guatemala", "Honduras", "Nicaragua", "Costa Rica", "Panama"},
		"Dominican Republic": {"Cuba", "Puerto Rico", "Mexico"},
		"Puerto Rico":        {"Cuba", "Dominican Republic", "Mexico", "Trinidad"},
		"Guatemala":          {"Mexico", "Honduras", "Belize", "El Salvador"},
		"Belize":             {"Mexico", "Honduras", "Guatemala"},
		"El Salvador":        {"Guatemala", "Honduras", "Nicaragua"},
		"Honduras":           {"Belize", "El Salvador", "Guatemala", "Nicaragua", "Cuba"},
		"Nicaragua":          {"Costa Rica", "Honduras", "Cuba"},
		"Costa Rica":         {"Nicaragua", "Panama"},
		"Panama":             {"Costa Rica", "Colombia"},
		"Colombia":           {"Panama", "Ecuador", "Venezuela", "Brazil"},
		"Ecuador":            {"Peru", "Colombia", "Brazil"},
		"Venezuela":          {"Guyana", "Colombia", "Brazil", "Trinidad"},
		"Trinidad":           {"Colombia", "Guyana", "Suriname", "French Guiana", "Puerto Rico"},
		"Guyana":             {"Venezuela", "Suriname", "Brazil"},
		"Suriname":           {"Guyana", "French Guiana", "Brazil", "Trinidad"},
		"French Guiana":      {"Suriname", "Brazil", "Trinidad"},
		"Peru":               {"Ecuador", "Bolivia", "Brazil", "Chile"},
		"Brazil":             {"Colombia", "Bolivia", "Venezuela", "Guyana", "French Guiana", "Suriname", "Uruguay", "Paraguay", "Argentina"},
		"Bolivia":            {"Brazil", "Peru", "Paraguay", "Argentina", "Chile"},
		"Paraguay":           {"Brazil", "Peru", "Bolivia", "Argentina"},
		"Chile":              {"Peru", "Argentina"},
		"Argentina":          {"Brazil", "Peru", "Paraguay", "Bolivia", "Chile", "Uruguay"},
		"Uruguay":            {"Brazil", "Argentina"},
	}
}
